### PR TITLE
example pull request

### PR DESCRIPTION
**Pull request by gtallen1187**
another one

### CODE REVIEW

**Comment by gtallen1187** [comment]
&nbsp;<b>Code Climate</b> has <a href="https://codeclimate.com/repos/554426f26956804030009d14/pull/3">analyzed this pull request</a>.

**Comment by gtallen1187** [comment]
@boxuancui  - check it out!

capture

**Comment by boxuancui** [comment]
There is no "#bo_photo", "#bo_name" and "#bo_title" in the DOM, and it still gives me 4.0?

**Comment by gtallen1187** [comment]
there isn't anything in the DOM - currently, the DOM doesn't even exist.  just your `.js` file right now.

**Comment by boxuancui** [comment]
So code climate just grades your script independently. It doesn't check for potential issues in the entire repo?

**Comment by gtallen1187** [comment]
@boxuancui - so that's what the other thing is for that i integrated into this repo - [Travis CI](https://travis-ci.org/HealthAPI/helmet).

**CodeClimate** is intended just to help you write high-quality code.  it analyzes the code you're writing indepently of any other files associated with it, and inspects it for unnecessary complexity, duplication, and all kinds of other stuff:

capture

**Travis CI** is the integration that actually ensures that your code _works_.  So for example, whenever we push code to a designated branch or via a pull request, Travis will actually check the code out on their own servers, and then run a set of build instructions.  If your code fails to execute during any of these various builds, you'll get an alert and a message that explains just exactly what went wrong.

This has saved me on more than one occasion, there i tried to merge code into production that i _thought_ i had tested, but missed a few things here and there.  Travis CI flagged it, automatically created an issue in the repo, then sent me an email basically saying "hey dumbass, what are you doing?"

**Comment by boxuancui** [comment]
Good.

**Pull request merged**
